name: "Build"
on:
  pull_request:
  push:
  schedule:
    - cron: '5 4 */2 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix-channel: ["nixos-22.05"]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: svenum 
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: '(-source$|nixpkgs\.tar\.gz$|nixexprs\.tar\.xz$)'
    - run: nix build --override-input nixpkgs "github:NixOS/nixpkgs/${{ matrix.nix-channel }}"
